title: Memoru's page
description: This site is my jotting notebook.

show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

github: [metadata]
encoding: UTF-8
kramdown:
   input: GFM
   hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

author: Mitz

lang: en
timezone: Asia/Tokyo

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - docker-compose.yml
  - vendor/

github_username: sakai-memoru
twitter_username: SakaiMemoru
